import asyncio
import logging
import uuid as uuid_lib
from datetime import datetime, timezone, timedelta
from typing import Dict, Any

from db.session import AsyncSessionLocal
from backend.models.models import User, Subscription, VPNKey, SubscriptionStatus, Payment, PaymentStatus
from backend.services.vpn import vpn_service
from backend.services.payments import cryptobot_service
from sqlalchemy import select

logger = logging.getLogger(__name__)

def generate_mock_config(user_id: int, uuid: str) -> str:
    """Generates a mock VLESS config as a fallback."""
    # This is a template for VLESS, adjust as needed for your server
    # vless://UUID@your-server:443?type=tcp&security=tls&sni=your-sni&fp=chrome&path=%2F&encryption=none#user_ID
    return f"vless://{uuid}@your-vpn-server.com:443?type=tcp&security=tls&sni=google.com&fp=chrome&path=%2F&encryption=none#user_{user_id}"

async def process_successful_payment(session, user_id: int, plan_days: int, amount: float, external_id: str):
    """Core logic for processing a successful payment, used by both webhook and polling."""
    # Idempotency check
    stmt = select(Payment).where(Payment.external_id == external_id)
    result = await session.execute(stmt)
    if result.scalar_one_or_none():
        return False

    # 1. Record payment
    payment = Payment(
        user_id=user_id,
        amount=amount,
        provider="cryptobot",
        status=PaymentStatus.COMPLETED,
        external_id=external_id
    )
    session.add(payment)
    
    # 2. Update/Create subscription
    now = datetime.now()
    end_date = now + timedelta(days=plan_days)
    
    sub = Subscription(
        user_id=user_id,
        plan=str(plan_days),
        start_date=now,
        end_date=end_date,
        status=SubscriptionStatus.ACTIVE
    )
    session.add(sub)
    await session.flush() # Get subscription ID
    
    # 3. Provision VPN (Always create record)
    # Get user telegram_id for RemnaWave
    user_stmt = select(User).where(User.id == user_id)
    user_res = await session.execute(user_stmt)
    user = user_res.scalar_one()

    vpn_data = await vpn_service.create_vpn_user(user.telegram_id, expire_at=int(end_date.timestamp()))
    
    config = None
    is_active = False
    uuid = None
    error_message = None

    if vpn_data.get("success"):
        # API worked
        data = vpn_data.get("data", {})
        if isinstance(data, dict):
            uuid = data.get("uuid") or data.get("id")
        
        if uuid:
            fetched_config = await vpn_service.get_vpn_config(uuid)
            if fetched_config:
                config = fetched_config
                is_active = True
            else:
                error_message = "Failed to fetch config after user creation"
        else:
            error_message = "No UUID/ID in success response"
    else:
        # API failed - record error
        error_message = vpn_data.get("error", "Unknown API error")
        logger.error(f"VPN Provisioning failed for user {user_id}: {error_message}")

    # Fallback: if no config was generated by API, create a mock one but keep is_active=False
    if not config:
        fallback_uuid = str(uuid_lib.uuid4())
        uuid = uuid or fallback_uuid
        config = generate_mock_config(user.telegram_id, uuid)
        # Note: is_active remains False, but user will see SOMETHING (with a warning in profile)
        # We will keep trying to fix this in the background task

    new_vpn = VPNKey(
        user_id=user_id,
        subscription_id=sub.id,
        uuid=uuid,
        config=config,
        expire_at=end_date,
        is_active=is_active,
        error_message=error_message
    )
    session.add(new_vpn)
    
    await session.commit()
    logger.info(f"Successfully processed payment {external_id} for user {user_id}. VPN Active: {is_active}")
    return True

async def check_expirations():
    """Background task to check for expired subscriptions."""
    while True:
        try:
            async with AsyncSessionLocal() as session:
                now = datetime.now()
                stmt = select(Subscription).where(
                    Subscription.end_date < now,
                    Subscription.status == SubscriptionStatus.ACTIVE
                )
                result = await session.execute(stmt)
                expired_subs = result.scalars().all()

                for sub in expired_subs:
                    logger.info(f"Subscription {sub.id} expired for user {sub.user_id}")
                    sub.status = SubscriptionStatus.EXPIRED
                    
                    vpn_stmt = select(VPNKey).where(VPNKey.user_id == sub.user_id)
                    vpn_res = await session.execute(vpn_stmt)
                    vpn_key = vpn_res.scalar_one_or_none()
                    
                    if vpn_key:
                        await vpn_service.disable_vpn_user(vpn_key.uuid)
                
                await session.commit()
        except Exception as e:
            logger.error(f"Error in expiration checker: {e}")
        await asyncio.sleep(300)

async def payment_polling():
    """Background task to poll CryptoBot for pending payments."""
    while True:
        try:
            async with AsyncSessionLocal() as session:
                # Get pending payments
                stmt = select(Payment).where(Payment.status == PaymentStatus.PENDING)
                result = await session.execute(stmt)
                pending_payments = result.scalars().all()
                
                if pending_payments:
                    invoice_ids = [p.external_id for p in pending_payments]
                    invoices = await cryptobot_service.get_invoices(invoice_ids)
                    
                    for invoice in invoices:
                        if invoice.get("status") == "paid":
                            external_id = str(invoice.get("invoice_id"))
                            amount = float(invoice.get("amount"))
                            payload = invoice.get("payload", "")
                            
                            if ":" in payload:
                                user_id, plan_days = map(int, payload.split(":"))
                                await process_successful_payment(session, user_id, plan_days, amount, external_id)
        except Exception as e:
            logger.error(f"Error in payment polling: {e}")
        await asyncio.sleep(20)

async def vpn_retry_task():
    """Background task to retry failed VPN key creations."""
    while True:
        try:
            async with AsyncSessionLocal() as session:
                # Get failed/inactive VPN keys that haven't expired
                stmt = select(VPNKey).where(
                    VPNKey.is_active == False,
                    VPNKey.expire_at > datetime.now()
                )
                result = await session.execute(stmt)
                failed_keys = result.scalars().all()

                for vpn_key in failed_keys:
                    logger.info(f"Retrying VPN creation for user {vpn_key.user_id} (VPNKey ID: {vpn_key.id})")
                    
                    # Get user telegram_id
                    user_stmt = select(User).where(User.id == vpn_key.user_id)
                    user_res = await session.execute(user_stmt)
                    user = user_res.scalar_one()

                    vpn_data = await vpn_service.create_vpn_user(
                        user.telegram_id, 
                        expire_at=int(vpn_key.expire_at.timestamp())
                    )

                    if vpn_data.get("success"):
                        uuid = vpn_data["data"].get("uuid")
                        if uuid:
                            config = await vpn_service.get_vpn_config(uuid)
                            if config:
                                vpn_key.uuid = uuid
                                vpn_key.config = config
                                vpn_key.is_active = True
                                vpn_key.error_message = None
                                logger.info(f"Successfully recovered VPN key for user {vpn_key.user_id}")
                            else:
                                vpn_key.error_message = "Recovery: Failed to fetch config"
                        else:
                            vpn_key.error_message = "Recovery: No UUID in success response"
                    else:
                        vpn_key.error_message = f"Recovery failed: {vpn_data.get('error')}"
                
                await session.commit()
        except Exception as e:
            logger.error(f"Error in VPN retry task: {e}")
        await asyncio.sleep(60) # Check every minute
